### PR TITLE
Adds RdSeed capability and support for AMD RdRand

### PR DESCRIPTION
**Pull request by dj-on-github**
These are the code changes I've proposed in the RdSeed issue I filed. There are some clarifications of the security in the text files (O(2^128) for RdRand and full entropy for RdSeed), RdSeedom is added to be the RdSeed variant of RdRandom. 

AMD now support RdRand and the associated CPUID bits, so I have updated the code to recognize that.  

For full entropy bits that can be safely concatenated into arbitarily large keys, use RdSeedom.

>>> from rdrand import RdRandom
>>> from rdseed import RdSeedom
>>> r = RdRandom()
>>> s = RdSeedom()
>>> hex(r.getrandbits(256))
'0xab1e6b41cab990d124616a96dd6a86f9b7e2430d29bffe65c80092156c238f24L'
>>> hex(r.getrandbits(256))
'0x8932afbd1c3e868c8c30ad1f460e4b12b4c9ccbfb4357e2b0c2d57217b652e25L'
>>> hex(s.getrandbits(256))
'0xcdf6f793315211f53af046cb6e10d58368d4763cfdb7c8116f155653dd4033abL'
>>> hex(s.getrandbits(256))
'0x7d862af64e3f7cb2ba7fdcab3c8821247f12feaadc518ff41930aad2b0dd922bL'
>>>

### CODE REVIEW

**Comment by stillson** [comment]
get around to pulling in rdseed changes.

Very likely needs some cleanup.

**Comment by dj-on-github** [comment]
I would be happy to see someone test it on AMD hardware to make sure it works.

**Comment by stillson** [comment]
You have untested code in this? I wish you had mentioned that. Could you tell me what you have tested and what you haven't?

**Comment by stillson** [comment]
Anyway, thanks for your contribution. I'm sorry it took me a while to get to this. Just got laid off because, well, Cisco.

I would like to consolidate rdrand.py and rdseed.py into one file. Actually, into one class with a parameter deciding if it uses seed or rand.

Also, lots of testing (freebsd, linux, and osx). I'll try to send you an email with some questions.

**Comment by dj-on-github** [comment]
Thanks for taking the pull. I was trying to code it with mimimal changes so
you could integrate it how you wish without untangling my edits.

I’ve tested it on macosx and linux. I’ve been working on a single file
cpuid and rdrand C library that will compile in Visual Studio, minGW, Linux
GCC, linux Clang and macos xcode. I’ll share it with you once Ive got it
fully tested.

Regards,
DJ

**Comment by stillson** [comment]
that would be great. I'll probably do the work to port it to freebsd clang also (which should be minimal if it works on macos)

**Pull request merged**
