### PR TITLE
Add an explicit LICENSE file.

### PR DESCRIPTION
**Pull request by yilei**

### CODE REVIEW

**Comment by yilei** [comment]
Hi Chris,

Would you mind add an explicit LICENSE file to this project?

Thanks,
Yilei

**Comment by yilei** [comment]
Kindly ping @stillson ?

**Review by stillson — APPROVED** [review]
lgtm

**Comment by stillson** [comment]
Sorry I didn't see your pull request last year.  Approved it as soon as I saw it. What are you going to use it for?

**Pull request merged**
